name: Get Wiki

on:
    push:
      branches: 
          -main
    workflow_dispatch:
    schedule:
      - cron: '0 0 * * *' # runs every day at midnight

jobs: 
    scrapewiki:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
              python-version: '3.10' 
        - run: pip install requests beautifulsoup4
        - run: python scrape.py
        - run: |
              git config --global user.email "avron.nir@gmail.com"
              git config --global user.name "niravron"
              git add .
              git commit -m "Do Automated Update"
              git push




